#Each new term in the Fibonacci sequence is generated by
#adding the previous two terms. By starting with 1 and 2, the
#first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose
#values do not exceed four million, find the sum of the
#even-valued terms.

.limit <- 4e6
f.fibb <- function(x0=1, x1=2, limit=10) {
    if (x1>limit ) return(x0)
    ## grow vector x0 as we go
    new.x0 <- c(x0, x1)
    new.x1 <- tail(x0,1)+x1
    ## need to hand limit along
    f.fibb(new.x0, new.x1, limit)
}
.ans <- f.fibb(limit=.limit)
## index of even elements
.is.even <- !(.ans %% 2)
.ans = sum(.ans[.is.even])

