#Each new term in the Fibonacci sequence is generated by
#adding the previous two terms. By starting with 1 and 2, the
#first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose
#values do not exceed four million, find the sum of the
#even-valued terms.

is.even <- function(x) !(x%%2)
.limit <- 4*10^(10^2)
#.limit <- 4e6
f.accum.fib <- function(x0=1, x1=1, accum=0, 
    ## set limit and test.fun at define-time
    limit=.limit, test.fun=is.even
) {
    ## hand accum along, 
    ## summing new fibs that are true for test.fun as we go
    new.x1 <- x0+x1
    ## done
    if (new.x1>limit ) return(accum)
    ## it's even (or whatever), accumulate the new fib
    if (test.fun(new.x1)) {
        f.accum.fib(x1, new.x1, accum=accum+new.x1)
    } else { 
        f.accum.fib(x1, new.x1, accum=accum)
    }
}
.ans <- f.accum.fib()

