## The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
     #1: 1
     #3: 1,3
     #6: 1,2,3,6
    #10: 1,2,5,10
    #15: 1,3,5,15
    #21: 1,3,7,21
    #28: 1,2,4,7,14,28

#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?


f.find.factors <- function(n, primes.vec) {
    ## convenience function, rows for count >0
    .f.sub <- function(f) f[ f[,'count']>0,]
    ret <- cbind(prime=primes.vec, count=0)
    for (ii in 1:nrow(ret)){
        .prime <- ret[ii,'prime']
        while ( (  n %% .prime ) == 0 ) {
            ret[ii,'count'] = ret[ii,'count'] + 1 
            n = n %/% .prime
        }
    }
    ## 
    ret <-  ret[ ret[,'count']>0,]
    ## add remainder if it exists
    if (n >1) {
        ret <- rbind(ret, c(n, 1))
    }
    return(ret)
}

.nfac <- 0
.nn <- 10
.limit <- 5e2
primes.vec <- f.primes.to(to=Inf, num=.limit)
while(.nfac <= .limit) {
    .nn <- .nn + 1
    .tri <- f.sum.to(.nn)
    .factors <- f.find.factors(.tri, primes.vec)
    .nfac <- prod(.factors[,'count']+1)
    #cat(paste0(.nn, '\t', .nfac, '\n'))
}
.ans <- .tri
            
